将更多附属汉化接入构建库
ybw0014/maven-builds pull request #120
Opened 2022-02-13 07:32 UTC by haiman233

2022-02-13 08:01 UTC, ybw0014 commented
先解决下冲突

2022-02-13 08:26 UTC, haiman233 commented
是啥原因冲突

2022-02-13 11:22 UTC, haiman233 commented
绝了，这冲突我不会修啊qwq

2022-02-13 20:56 UTC, ybw0014 requested changes
如果不会解决冲突，重新fork然后编辑

2022-02-13 20:56 UTC, ybw0014 commented on static/repos.json
> +	"baoad/SlimyRepair:master": {
不要使用tab，用空格

2022-02-14 03:09 UTC, ybw0014 commented
Handled in #123

2022-02-14 03:09 UTC, closed without merging